[package]
name = "firmware_common"
version = "0.1.0"
authors = ["david"]

[dependencies]
bitflags = "*"
hmac = "*"
md-5 = "*"
stm32f0xx = { git = "https://github.com/dtwood/stm32f0xx" }
stm32f0xx-hal = { git = "https://github.com/dtwood/stm32f0xx" }
rfm95w = { path = "../rfm95w" }
