[package]
name = "firmware_common"
version = "0.1.0"
authors = ["david"]

[dependencies]
md-5 = "*"
hmac = "*"
f0 = { path = "../f0" }
libopencm3-sys = { path = "../libopencm3-sys" }

[build-dependencies]
gcc = "*"
libopencm3-sys = { path = "../libopencm3-sys" }
