[package]
name = "f0"
version = "0.1.0"
authors = ["David Wood <devel@dtwood.uk>"]

[dependencies]
bare-metal = "*"
embedded-hal = { git = "https://github.com/japaric/embedded-hal" }
nb = { git = "https://github.com/japaric/nb" }
stm32f0xx = { path = "../stm32f0xx" }
